### ISSUE TITLE
Doesn't appear to work with Safari 8.0.2

### ISSUE THREAD

**Issue by scottyob** [0a-/meteor-ace-editor#1]
Doesn't appear to work on Safari, Chrome and Firefox are cool though.

[Log] even ActiveXObject('Microsoft.request') doesn't work :( (arch_ace-editor.js, line 44)

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Thanks for pointing it out! I just got it fixed and published 1.2.2. Apparently, in Safari the typeof `XMLHttpRequest` is an object but not a function. So I should have written `if(window.XMLHttpRequest)` instead of `if(typeof XMLHttpRequest === 'function')` in line 3.
