### ISSUE TITLE
Getting value of editor

### ISSUE THREAD

**Issue by sangyoo91** [0a-/meteor-ace-editor#2]
```
setTimeout(function() {
    var content = $('#content').val();
    Session.set('content', content);
}, 1000
```

So I have a code I use to use like this to generate a Session to see preview of a textarea,

How would I get the value from the editor and set it to a session in this package?

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
> To learn more about Ace Editor, you can read [the how-to guide](http://ace.c9.io/#nav=howto) on their website. 

As for your question, it was answered under the `Common Operations` session.
