### ISSUE TITLE
undoManager?

### ISSUE THREAD

**Issue by mkarliner** [0a-/meteor-ace-editor#4]
It seems that the default editor is created without an undoManager.
I can't quite see how to set one either, as I can't see an undoManager define anywhere.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Sorry it took me so long to response. When I first saw this I thought this feature required a deep dive into their source but it appears that undoManager is accessible at window.ace.UndoManager. So `new window.ace.UndoManager` would create an undo manager usable as described in the api.
