### ISSUE TITLE
Problem with eval() when I instantiate AceEditor

### ISSUE THREAD

**Issue by acadeau** [0a-/meteor-ace-editor#7]
Hi,
I would like to use your package but I have this error when I try to instantiate AceEditor : 
`/packages/arch_ace-editor/ace-builds/src-noconflict/ace.js is loaded but can't be eval(), man!`
With break point, I find the error  : 
`"Cannot set property 'packaged' of undefined"`

The stacktrace : 

```
"TypeError: Cannot set property 'packaged' of undefined at exportAce (eval at <anonymous> (http://127.0.0.1:3000/packages/arch_ace-editor.js?0f2bd0cc9db9bef9ee266012fca459e7a3589c7b:53:33), 
<anonymous>:175:30) at eval (eval at <anonymous> (http://127.0.0.1:3000/packages/arch_ace-editor.js?0f2bd0cc9db9bef9ee266012fca459e7a3589c7b:53:33), 
<anonymous>:185:1) at eval (eval at <anonymous> (http://127.0.0.1:3000/packages/arch_ace-editor.js?0f2bd0cc9db9bef9ee266012fca459e7a3589c7b:53:33),
<anonymous>:187:3) at eval (native) at http://127.0.0.1:3000/packages/arch_ace-editor.js?0f2bd0cc9db9bef9ee266012fca459e7a3589c7b:53:33 at XMLHttpRequest.request.onreadystatechange (http://127.0.0.1:3000/packages/arch_ace-editor.js?0f2bd0cc9db9bef9ee266012fca459e7a3589c7b:54:19)"
```

The code in ace.js (line 175): 
`root.define.packaged = true;`
The logic is `define` is undefined, but I don't know why. 

 My code (I use Angular-Meteor) : 
EditorController.js

```
angular.module('share')
  .controller("EditorController", ['$scope', function($scope){
    var ace = AceEditor.instance("archy",{
        theme:"dawn",
        mode:"html"
    });
  }]);
```

editor.ng.html:
`<pre id="archy"></pre>`

Have you any idea ?

**Comment by acadeau** [comment]
Ok, now it works, don't know why :). 

Thank you.

PS : the error is still there, but the editor works :).
PS2 : You've made a good job ! Thank you !

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Hi. Glad that the ace editor is working. 

I've just looked into the ace's code:

``` javascript
function exportAce(ns) {
    var require = function(module, callback) {
        return _require("", module, callback);
    };

    var root = global;
    if (ns) {
        if (!global[ns])
            global[ns] = {};
        root = global[ns];
    }

    if (!root.define || !root.define.packaged) {
        _define.original = root.define;
        root.define = _define;
        root.define.packaged = true;
    }

    if (!root.require || !root.require.packaged) {
        _require.original = root.require;
        root.require = require;
        root.require.packaged = true;
    }
}

exportAce(ACE_NAMESPACE);
```

basically it looks up to see if `root.define` is defined before `root.define.packaged = true;`. So the type error that you see is really strange. But if it is working that means that line doesn't throw an exception now. 

By the error is still there, do you mean you are still seeing this line: `/packages/arch_ace-editor/ace-builds/src-noconflict/ace.js is loaded but can't be eval(), man!`?

can you tell me what browser you are using? And if possible, can you try adding this line of code `window.eval.call( window, "evaluated" );` in your callback to `.controller` and let me know what happens in the console?

**Comment by acadeau** [comment]
> By the error is still there, do you mean you are still seeing this line: /packages/arch_ace-editor/ace-builds/src-noconflict/ace.js is loaded but can't be eval(), man!?

Yes, I have this error on Firefox and Chrome.

> And if possible, can you try adding this line of code window.eval.call( window, "evaluated" ); in your callback to .controller and let me know what happens in the console?

I've got this `ReferenceError: evaluated is not defined` when I add `window.eval.call( window, "evaluated" );`.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Opps my bad, strings are parsed as lines of code before being evaluated in Javascript unlike in Scheme and similar languages where the notion of [_symbols_](https://en.wikipedia.org/wiki/Symbol_%28programming%29) is used instead (so if you evaluate a string it would just print out the string), and that is likely why you are seeing `/packages/arch_ace-editor/ace-builds/src-noconflict/ace.js is loaded but can't be eval(), man!?` which shouldn't show up. If you try `window.eval.call( window, "\"evaluated\"" );` you would now see "evaluated" printed out in the console.

Thanks man. So the error here is that the error message is being logged in the case when there is no error. I would get this fixed in these few days.

**Comment by acadeau** [comment]
Ok, I have learned something :p. 
Thank you !

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Finally got the time to re-go through my old code & their logic. Oops. My interpretation was wrong. Turned out my `eval` was there to load the whole script (rather than just printing text). If the editor works you shouldn't be seeing the error. Do you still see the error now?
